// @vitest-environment jsdom
import type { CareerCategory, CareerRecord, CareerViewConfiguration } from "@expresso/contracts";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const push=vi.fn(); vi.mock("next/navigation",()=>({useRouter:()=>({push})}));
vi.mock("@/app/(app)/career/[categorySlug]/DocumentPanel",()=>({DocumentPanel:({record,onExpand}:{record:CareerRecord|null;onExpand?:()=>void})=><aside aria-label="문서 패널 테스트"><span>{record?.title}</span><button onClick={onExpand}>넓게 보기</button></aside>}));
import { CareerViewShell } from "./CareerViewShell";

const categoryId="00000000-0000-4000-8000-000000000001", titleId="00000000-0000-4000-8000-000000000002", dateId="00000000-0000-4000-8000-000000000003";
const category:CareerCategory={id:categoryId,key:"test",name:"테스트",icon:"table",defaultView:"table",isSystem:false,propertySchema:{},propertySchemaV2:[{id:titleId,key:"title",name:"제목",type:"title",required:true,system:true,config:{},order:0,version:1,deletedAt:null},{id:dateId,key:"date",name:"날짜",type:"date",required:false,system:false,config:{},order:1,version:1,deletedAt:null}],schemaVersion:1,sortOrder:0,recordCount:2,version:1};
const records:CareerRecord[]=[1,2].map(index=>({id:`00000000-0000-4000-8000-00000000000${index+3}`,categoryId,title:`기록 ${index}`,status:index===1?"draft":"verified",origin:"manual",properties:{date:{type:"date",value:{start:`2026-09-0${index}`,end:null,timezone:null}}},bodyMd:"",version:1,updatedAt:"2026-09-01T00:00:00.000Z"}));
const initial:CareerViewConfiguration={id:`local-${categoryId}`,categoryId,name:"기본 뷰",type:"table",version:1,order:0,filter:null,sorts:[],groupPropertyId:null,groupOrder:[],recordOrder:[],visiblePropertyIds:[titleId,dateId],propertyOrder:[titleId,dateId],columnWidths:{},gallery:null,board:null,timeline:null,createdAt:"2026-09-01T00:00:00.000Z",updatedAt:"2026-09-01T00:00:00.000Z"};

describe("CareerViewShell",()=>{beforeEach(()=>{push.mockReset();vi.stubGlobal("fetch",vi.fn(async(url:string,init?:RequestInit)=>{const body=init?.body?JSON.parse(String(init.body)):{};if(url==="/api/career/records")return new Response(JSON.stringify({data:{...records[0],id:"00000000-0000-4000-8000-000000000009",title:""}}),{status:200,headers:{"content-type":"application/json"}});if(url.includes("/api/career/records/"))return new Response(JSON.stringify({data:{...records[0],status:body.status,version:2}}),{status:200,headers:{"content-type":"application/json"}});if(url.includes("duplicate"))return new Response(JSON.stringify({data:{...initial,id:titleId,name:"복제"}}),{status:200,headers:{"content-type":"application/json"}});return new Response(JSON.stringify({data:{...initial,...body,id:titleId,version:2}}),{status:200,headers:{"content-type":"application/json"}})}));});afterEach(cleanup);
 it("keeps the document drawer closed until a record is opened",()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getByLabelText("문서 패널 테스트").textContent).not.toContain("기록 1");fireEvent.click(screen.getByRole("gridcell",{name:"기록 1"}));expect(screen.getByLabelText("문서 패널 테스트").textContent).toContain("기록 1");});
 it("switches among five accessible renderers and supports roving keyboard focus",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getByRole("grid",{name:"커리어 테이블"})).toBeTruthy();for(const [tab,role,name] of [["목록","list","커리어 목록"],["갤러리","list","커리어 갤러리"],["보드","generic","커리어 보드"],["타임라인","list","커리어 타임라인"],["테이블","grid","커리어 테이블"]] as const){fireEvent.click(screen.getByRole("tab",{name:tab}));await waitFor(()=>expect(screen.getByRole(role,{name})).toBeTruthy());}const row=screen.getByRole("row",{name:/기록 1/});fireEvent.keyDown(row,{key:"ArrowDown"});expect(screen.getByLabelText("문서 패널 테스트").textContent).toContain("기록 2");});
 it("creates records, bulk-updates status, persists settings, duplicates and opens full page",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:"새로 만들기"}));await waitFor(()=>expect(screen.getAllByLabelText(/선택/).length).toBeGreaterThan(2));fireEvent.click(screen.getByLabelText("기록 1 선택"));fireEvent.click(screen.getByRole("button",{name:"정리됨"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/api/career/records/"),expect.anything()));fireEvent.click(screen.getByRole("button",{name:"필터"}));fireEvent.click(screen.getByRole("button",{name:"필터 속성"}));fireEvent.click(screen.getByRole("option",{name:"날짜"}));expect(document.querySelector("select")).toBeNull();await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("view-configurations"),expect.anything()));fireEvent.click(screen.getByRole("button",{name:"＋ 뷰 추가"}));fireEvent.click(screen.getByRole("button",{name:"넓게 보기"}));expect(push).toHaveBeenCalledWith("/career/records/00000000-0000-4000-8000-000000000009");});
 it("keeps filter, sort and property controls in separate popovers",()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:/^필터$/}));expect(screen.getByRole("region",{name:"필터 설정"})).toBeTruthy();expect(screen.queryByRole("region",{name:"정렬 설정"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:/^정렬$/}));expect(screen.queryByRole("region",{name:"필터 설정"})).toBeNull();expect(screen.getByRole("region",{name:"정렬 설정"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/^속성$/}));expect(screen.queryByRole("region",{name:"정렬 설정"})).toBeNull();expect(screen.getByRole("region",{name:"표시 속성 설정"})).toBeTruthy();expect(screen.queryByRole("region",{name:"뷰 설정"})).toBeNull();fireEvent.keyDown(document,{key:"Escape"});expect(screen.queryByRole("region",{name:"표시 속성 설정"})).toBeNull();});
 it.each([
  ["experience",["테이블","보드","타임라인"],"대화로 꺼낸 순간들을 문서로 관리합니다."],
  ["project",["갤러리","테이블","타임라인"],"무엇을 만들었고 무엇이 달라졌는지."],
  ["education_history",["타임라인","테이블","갤러리"],"학교와 회사를 시간순으로."],
 ] as const)("keeps the screen-definition view order for %s",(key,tabs,blurb)=>{render(<CareerViewShell category={{...category,key,name:key}} initialView={{...initial,type:tabs[0]==="갤러리"?"gallery":tabs[0]==="타임라인"?"timeline":"table"}} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getAllByRole("tab").map(item=>item.textContent)).toEqual(tabs);expect(screen.getByText(new RegExp(blurb))).toBeTruthy();for(const action of ["＋ 뷰 추가","필터","정렬","속성","새로 만들기","AI로 만들기"])expect(screen.getByRole("button",{name:action})).toBeTruthy();});
 it("matches the project gallery information hierarchy",()=>{render(<CareerViewShell category={{...category,key:"project",name:"프로젝트",defaultView:"gallery"}} initialView={{...initial,type:"gallery",gallery:{coverPropertyId:null,previewPropertyIds:[]}}} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getByLabelText("커리어 갤러리")).toBeTruthy();expect(screen.getByRole("button",{name:/프로젝트 추가/})).toBeTruthy();expect(screen.getByText("2개 · 성과 수치 없음 2")).toBeTruthy();});
 it("filters records immediately and opens the guided AI questions",()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:/검증됨 1/}));expect(screen.getByRole("row",{name:/기록 2/})).toBeTruthy();expect(screen.queryByRole("row",{name:/기록 1/})).toBeNull();fireEvent.click(screen.getByRole("button",{name:"AI로 만들기"}));expect(screen.getByRole("dialog").textContent).toContain("기록 시작하기");});
 it("routes the project missing-outcome action into guided questions",()=>{render(<CareerViewShell category={{...category,key:"project",name:"프로젝트",defaultView:"gallery"}} initialView={{...initial,type:"gallery",gallery:{coverPropertyId:null,previewPropertyIds:[]}}} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:"비어 있는 성과 채우기"}));expect(screen.getByRole("dialog").textContent).toContain("보완하기");});
});
