"use client";
import type { CareerCategory, CareerRecord, CareerRecordListItem, CareerViewConfiguration } from "@expresso/contracts";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { BoardView } from "./BoardView"; import { GalleryView } from "./GalleryView"; import { ListView } from "./ListView"; import { TableView } from "./TableView"; import { TimelineView } from "./TimelineView"; import { ViewToolbar } from "./ViewToolbar";
import { DocumentPanel } from "@/app/(app)/career/[categorySlug]/DocumentPanel";
import { Icon } from "@/components/ui/Icon";
import styles from "./views.module.css";

export interface CareerViewPage { data: CareerRecord[]; page:{hasNextPage:boolean;nextCursor:string|null} }
export interface CareerViewShellProps { category:CareerCategory; initialView:CareerViewConfiguration; initialPage:CareerViewPage }
function listItem(record:CareerRecord):CareerRecordListItem{return {...record,categoryKey:"",isEmpty:record.title===""&&record.bodyMd===""&&Object.keys(record.properties).length===0,periodFrom:null,periodTo:null,linkCount:0,usedInCount:0};}
const BLURB:Record<string,string>={experience:"대화로 꺼낸 순간들을 문서로 관리합니다. 직접 쓰거나, 바리스타에게 질문을 받아 채울 수 있습니다.",project:"무엇을 만들었고 무엇이 달라졌는지. 성과 수치가 비어 있으면 AI가 먼저 물어봅니다.",education_history:"학교와 회사를 시간순으로. 각 항목 안에서 무엇을 했는지는 프로젝트·경험과 연결됩니다.",certification_award:"발급 기관과 취득일, 증빙까지 한 곳에 둡니다.",academic_writing:"논문 · 기술 글 · 발표를 한 곳에. 외부 링크의 조회와 인용은 자동으로 따라옵니다.",activity_leadership:"조직에서 맡은 역할과 규모를 남깁니다.",skill_tool:"직접 고르지 않아도 됩니다. 기록에 등장한 도구를 세어 자동으로 채웠고, 숙련도는 근거 개수로 계산합니다."};
const CATEGORY_ICON:Record<string,string>={experience:"chat-circle-dots",project:"briefcase",education_history:"graduation-cap",certification_award:"certificate",academic_writing:"article",activity_leadership:"users-three",skill_tool:"code"};
export function CareerViewShell({category,initialView,initialPage}:CareerViewShellProps){
 const router=useRouter(); const [view,setView]=useState(initialView); const [records,setRecords]=useState(()=>initialPage.data.map(listItem)); const [page,setPage]=useState(initialPage.page); const [activeId,setActiveId]=useState<string|null>(null); const [selected,setSelected]=useState<Set<string>>(new Set()); const [message,setMessage]=useState("");
 const active=records.find(r=>r.id===activeId)??null; const focusId=activeId??records[0]?.id??null; const common={records,view,category,activeId:focusId,openId:activeId,selectedIds:selected,onActivate:setActiveId,onCreate:()=>void create(),onToggle:(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;})};
 async function create(){const response=await fetch("/api/career/records",{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({categoryId:category.id,title:"",properties:{},bodyMd:""})});if(!response.ok)return setMessage("기록을 만들지 못했습니다.");const payload=await response.json() as {data:CareerRecord};const item=listItem(payload.data);setRecords(current=>[item,...current]);setActiveId(item.id);}
 async function updateView(next:CareerViewConfiguration){setView(next);const body={name:next.name,type:next.type,filter:next.filter,sorts:next.sorts,groupPropertyId:next.groupPropertyId,groupOrder:next.groupOrder,visiblePropertyIds:next.visiblePropertyIds,propertyOrder:next.propertyOrder,columnWidths:next.columnWidths,gallery:next.gallery,board:next.board,timeline:next.timeline};const local=next.id.startsWith("local-");const response=await fetch(local?`/api/career/categories/${category.id}/view-configurations`:`/api/career/view-configurations/${next.id}`,{method:local?"POST":"PATCH",headers:{"content-type":"application/json","if-match":`"v${local?category.version:view.version}"`},body:JSON.stringify(body)});if(!response.ok){setView(view);setMessage("뷰 변경을 저장하지 못했습니다.");return;}const payload=await response.json() as {data:CareerViewConfiguration};setView(payload.data);}
 async function duplicate(){if(view.id.startsWith("local-"))return setMessage("뷰를 먼저 저장해 주세요.");const response=await fetch(`/api/career/view-configurations/${view.id}/duplicate`,{method:"POST",headers:{"content-type":"application/json","if-match":`"v${view.version}"`},body:JSON.stringify({name:`${view.name} 복제`})});setMessage(response.ok?"뷰를 복제했습니다.":"뷰를 복제하지 못했습니다.");}
 async function bulkStatus(status:CareerRecord["status"]){for(const record of records.filter(r=>selected.has(r.id))){const response=await fetch(`/api/career/records/${record.id}`,{method:"PATCH",headers:{"content-type":"application/json","if-match":`"v${record.version}"`},body:JSON.stringify({status})});if(response.ok){const payload=await response.json() as {data:CareerRecord};setRecords(current=>current.map(item=>item.id===record.id?{...item,...payload.data}:item));}}setSelected(new Set());}
 async function more(){if(!page.nextCursor||view.id.startsWith("local-"))return;const response=await fetch(`/api/career/view-configurations/${view.id}/query?cursor=${encodeURIComponent(page.nextCursor)}&limit=50`);if(!response.ok)return;const payload=await response.json() as CareerViewPage;setRecords(current=>[...current,...payload.data.map(listItem)]);setPage(payload.page);}
 const renderer=view.type==="table"?<TableView {...common}/>:view.type==="list"?<ListView {...common}/>:view.type==="gallery"?<GalleryView {...common}/>:view.type==="board"?<BoardView {...common}/>:<TimelineView {...common}/>;
 return <div className={styles.shell}><main className={styles.viewArea}><div className={styles.categoryIntro}><span className={styles.categoryIcon}><Icon name={CATEGORY_ICON[category.key]??"file-text"} weight="fill" size={18}/></span><h1>{category.name}</h1><span className={styles.caret} aria-hidden="true"/></div><p className={styles.categoryBlurb}>{BLURB[category.key]??"이 카테고리의 기록입니다."}</p><ViewToolbar category={category} view={view} onChange={updateView} onCreate={()=>void create()} onDuplicate={duplicate}/>{selected.size?<div className={styles.bulk} role="toolbar" aria-label="선택한 기록 작업"><span>{selected.size}개 선택</span><button onClick={()=>void bulkStatus("draft")}>초안</button><button onClick={()=>void bulkStatus("organized")}>정리됨</button><button onClick={()=>void bulkStatus("verified")}>검증됨</button></div>:null}{message?<p role="status" className={styles.message}>{message}</p>:null}{renderer}{page.hasNextPage?<button className={styles.more} onClick={()=>void more()}>더 보기</button>:null}</main><DocumentPanel record={active} category={category} onClose={()=>setActiveId(null)} {...(active?{onExpand:()=>router.push(`/career/records/${active.id}` as never)}:{})}/></div>;
}
