// @vitest-environment jsdom
import type { CareerCategory, CareerRecord, CareerViewConfiguration } from "@expresso/contracts";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const push=vi.fn(); vi.mock("next/navigation",()=>({useRouter:()=>({push})}));
vi.mock("@/app/(app)/career/[categorySlug]/DocumentPanel",()=>({DocumentPanel:({record,onExpand}:{record:CareerRecord|null;onExpand?:()=>void})=><aside aria-label="문서 패널 테스트"><span>{record?.title}</span><button onClick={onExpand}>넓게 보기</button></aside>}));
import { CareerViewShell } from "./CareerViewShell";

const categoryId="00000000-0000-4000-8000-000000000001", titleId="00000000-0000-4000-8000-000000000002", dateId="00000000-0000-4000-8000-000000000003";
const category:CareerCategory={id:categoryId,key:"test",name:"테스트",icon:"table",defaultView:"table",isSystem:false,propertySchema:{},propertySchemaV2:[{id:titleId,key:"title",name:"제목",type:"title",required:true,system:true,config:{},order:0,version:1,deletedAt:null},{id:dateId,key:"date",name:"날짜",type:"date",required:false,system:false,config:{},order:1,version:1,deletedAt:null}],schemaVersion:1,sortOrder:0,recordCount:2,version:1};
const records:CareerRecord[]=[1,2].map(index=>({id:`00000000-0000-4000-8000-00000000000${index+3}`,categoryId,title:`기록 ${index}`,status:index===1?"draft":"verified",origin:"manual",properties:{date:{type:"date",value:{start:`2026-09-0${index}`,end:null,timezone:null}}},bodyMd:"",version:1,updatedAt:"2026-09-01T00:00:00.000Z"}));
const initial:CareerViewConfiguration={id:`local-${categoryId}`,categoryId,name:"기본 뷰",type:"table",version:1,order:0,filter:null,sorts:[],groupPropertyId:null,groupOrder:[],recordOrder:[],visiblePropertyIds:[titleId,dateId],propertyOrder:[titleId,dateId],columnWidths:{},gallery:null,board:null,timeline:null,createdAt:"2026-09-01T00:00:00.000Z",updatedAt:"2026-09-01T00:00:00.000Z"};

describe("CareerViewShell",()=>{beforeEach(()=>{push.mockReset();vi.stubGlobal("fetch",vi.fn(async(url:string,init?:RequestInit)=>{const body=init?.body?JSON.parse(String(init.body)):{};if(url==="/api/career/records")return new Response(JSON.stringify({data:{...records[0],id:"00000000-0000-4000-8000-000000000009",title:""}}),{status:200,headers:{"content-type":"application/json"}});if(url.includes("/api/career/records/"))return new Response(JSON.stringify({data:{...records[0],...body,version:2}}),{status:200,headers:{"content-type":"application/json"}});if(url.includes("duplicate"))return new Response(JSON.stringify({data:{...initial,id:titleId,name:"복제"}}),{status:200,headers:{"content-type":"application/json"}});return new Response(JSON.stringify({data:{...initial,...body,id:titleId,version:2}}),{status:200,headers:{"content-type":"application/json"}})}));});afterEach(cleanup);
 it("opens the document drawer from the title cell",()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getByLabelText("문서 패널 테스트").textContent).not.toContain("기록 1");fireEvent.click(screen.getByRole("gridcell",{name:"기록 1"}));expect(screen.getByLabelText("문서 패널 테스트").textContent).toContain("기록 1");});
 it("switches among five accessible renderers and supports roving keyboard focus",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getByRole("grid",{name:"커리어 테이블"})).toBeTruthy();for(const [tab,role,name] of [["목록","list","커리어 목록"],["갤러리","list","커리어 갤러리"],["보드","generic","커리어 보드"],["타임라인","list","커리어 타임라인"],["테이블","grid","커리어 테이블"]] as const){fireEvent.click(screen.getByRole("tab",{name:tab}));await waitFor(()=>expect(screen.getByRole(role,{name})).toBeTruthy());}const row=screen.getByRole("row",{name:/기록 1/});fireEvent.keyDown(row,{key:"ArrowDown"});expect(screen.getByLabelText("문서 패널 테스트").textContent).toContain("기록 2");});
 it("creates records, bulk-updates status, persists settings, duplicates and opens full page",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:"새로 만들기"}));await waitFor(()=>expect(screen.getAllByLabelText(/선택/).length).toBeGreaterThan(2));fireEvent.click(screen.getByLabelText("기록 1 선택"));fireEvent.click(screen.getByRole("button",{name:"정리됨"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/api/career/records/"),expect.anything()));fireEvent.click(screen.getByRole("button",{name:"필터"}));fireEvent.click(screen.getByRole("button",{name:"필터 속성"}));fireEvent.click(screen.getByRole("option",{name:"날짜"}));expect(document.querySelector("select")).toBeNull();await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("view-configurations"),expect.anything()));fireEvent.click(screen.getByRole("button",{name:"＋ 뷰 추가"}));fireEvent.click(screen.getByRole("button",{name:"넓게 보기"}));expect(push).toHaveBeenCalledWith("/career/records/00000000-0000-4000-8000-000000000009");});
 it("sends grouped quick-add as a canonical initial PropertyValue",async()=>{const optionId="00000000-0000-4000-8000-000000000020";const selectId="00000000-0000-4000-8000-000000000021";const groupedCategory={...category,propertySchemaV2:[...(category.propertySchemaV2??[]),{id:selectId,key:"stage",name:"단계",type:"select" as const,required:false,system:false,config:{options:[{id:optionId,name:"지원"}]},order:2,version:1,deletedAt:null}]};const groupedView={...initial,groupPropertyId:selectId};const groupedRecords=records.map((record,index)=>index===0?{...record,propertyValues:[{propertyDefinitionId:selectId,type:"select" as const,value:optionId}]}:record);render(<CareerViewShell category={groupedCategory} initialView={groupedView} initialPage={{data:groupedRecords,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:"지원 그룹에 새 기록"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith("/api/career/records",expect.objectContaining({method:"POST",body:JSON.stringify({categoryId,propertyValues:[{propertyDefinitionId:selectId,type:"select",value:optionId}]})})));});
 it("marks record duplication explicitly for the Spring compatibility create path",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.contextMenu(screen.getByRole("gridcell",{name:"기록 1"}),{clientX:10,clientY:10});fireEvent.click(screen.getByRole("menuitem",{name:"기록 복제"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith("/api/career/records",expect.objectContaining({method:"POST",body:JSON.stringify({createMode:"duplicate",categoryId,title:"기록 1 복제",properties:records[0]!.properties,bodyMd:records[0]!.bodyMd})})));});
 it("duplicates canonical values without projecting them through legacy properties",async()=>{const precise={...records[0]!,propertyValues:[{propertyDefinitionId:dateId,type:"date" as const,value:{precision:"month" as const,start:"2026-01",end:"2026-03",timezone:null}}]};render(<CareerViewShell category={category} initialView={initial} initialPage={{data:[precise],page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.contextMenu(screen.getByRole("gridcell",{name:"기록 1"}),{clientX:10,clientY:10});fireEvent.click(screen.getByRole("menuitem",{name:"기록 복제"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith("/api/career/records",expect.objectContaining({method:"POST",body:JSON.stringify({createMode:"duplicate",categoryId,title:"기록 1 복제",properties:precise.properties,bodyMd:precise.bodyMd,propertyValues:precise.propertyValues})})));});
 it("keeps filter, sort and property controls in separate popovers",()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:/^필터$/}));expect(screen.getByRole("region",{name:"필터 설정"})).toBeTruthy();expect(screen.queryByRole("region",{name:"정렬 설정"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:/^정렬$/}));expect(screen.queryByRole("region",{name:"필터 설정"})).toBeNull();expect(screen.getByRole("region",{name:"정렬 설정"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/^속성$/}));expect(screen.queryByRole("region",{name:"정렬 설정"})).toBeNull();expect(screen.getByRole("region",{name:"표시 속성 설정"})).toBeTruthy();expect(screen.queryByRole("region",{name:"뷰 설정"})).toBeNull();fireEvent.keyDown(document,{key:"Escape"});expect(screen.queryByRole("region",{name:"표시 속성 설정"})).toBeNull();});
 it.each([
  ["experience",["테이블","보드","타임라인"],"대화로 꺼낸 순간들을 문서로 관리합니다."],
  ["project",["갤러리","테이블","타임라인"],"무엇을 만들었고 무엇이 달라졌는지."],
  ["education_history",["타임라인","테이블","갤러리"],"학교와 회사를 시간순으로."],
 ] as const)("keeps the screen-definition view order for %s",(key,tabs,blurb)=>{render(<CareerViewShell category={{...category,key,name:key}} initialView={{...initial,type:tabs[0]==="갤러리"?"gallery":tabs[0]==="타임라인"?"timeline":"table"}} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getAllByRole("tab").map(item=>item.textContent)).toEqual(tabs);expect(screen.getByText(new RegExp(blurb))).toBeTruthy();for(const action of ["＋ 뷰 추가","필터","정렬","속성","새로 만들기"])expect(screen.getByRole("button",{name:action})).toBeTruthy();expect(screen.queryByRole("button",{name:"AI로 만들기"})).toBeNull();});
 it("matches the project gallery information hierarchy",()=>{render(<CareerViewShell category={{...category,key:"project",name:"프로젝트",defaultView:"gallery"}} initialView={{...initial,type:"gallery",gallery:{coverPropertyId:null,previewPropertyIds:[]}}} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.getByLabelText("커리어 갤러리")).toBeTruthy();expect(screen.getByRole("button",{name:/프로젝트 추가/})).toBeTruthy();expect(screen.getByText("2개 · 성과 수치 없음 2")).toBeTruthy();});
 it("filters records immediately without exposing the guided AI entrypoint",()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);fireEvent.click(screen.getByRole("button",{name:/검증됨 1/}));expect(screen.getByRole("row",{name:/기록 2/})).toBeTruthy();expect(screen.queryByRole("row",{name:/기록 1/})).toBeNull();expect(screen.queryByRole("button",{name:"AI로 만들기"})).toBeNull();});
 it("hides the project missing-outcome AI action",()=>{render(<CareerViewShell category={{...category,key:"project",name:"프로젝트",defaultView:"gallery"}} initialView={{...initial,type:"gallery",gallery:{coverPropertyId:null,previewPropertyIds:[]}}} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);expect(screen.queryByRole("button",{name:"비어 있는 성과 채우기"})).toBeNull();});
 it("optimistically saves table cells in the background",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);const title=screen.getByRole("gridcell",{name:"기록 1"});fireEvent.focus(title);fireEvent.keyDown(title,{key:"F2"});const input=screen.getByRole("textbox",{name:"제목 셀 편집"});fireEvent.change(input,{target:{value:"수정된 기록"}});fireEvent.keyDown(input,{key:"Enter"});await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining(`/api/career/records/${records[0]!.id}`),expect.objectContaining({method:"PATCH",body:JSON.stringify({title:"수정된 기록"})})));expect(screen.queryByText("저장 중...")).toBeNull();await waitFor(()=>expect(screen.getByText("수정된 기록").closest('[role="gridcell"]')).toBeTruthy());});
 it("trashes a record with its current version",async()=>{render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);const title=screen.getByRole("gridcell",{name:"기록 1"});fireEvent.contextMenu(title,{clientX:10,clientY:10});fireEvent.click(screen.getByRole("menuitem",{name:"기록 삭제"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(`/api/career/records/${records[0]!.id}`,expect.objectContaining({method:"DELETE",headers:expect.objectContaining({"if-match":'"v1"'})})));});
 it("sends the complete canonical snapshot when one property changes",async()=>{const canonicalRecords=records.map((record,index)=>({...record,propertyValues:[{propertyDefinitionId:dateId,type:"date" as const,value:{precision:"day" as const,start:`2026-09-0${index+1}`,end:null}}]}));render(<CareerViewShell category={category} initialView={initial} initialPage={{data:canonicalRecords,page:{hasNextPage:false,nextCursor:null}}}/>);const date=screen.getByRole("gridcell",{name:"2026-09-01"});fireEvent.click(date);fireEvent.click(date);const dialog=screen.getByRole("dialog",{hidden:true});const nextDay=[...dialog.querySelectorAll("button")].find(button=>button.textContent==="2");expect(nextDay).toBeTruthy();fireEvent.click(nextDay!);await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining(`/api/career/records/${canonicalRecords[0]!.id}`),expect.objectContaining({method:"PATCH",body:JSON.stringify({propertyValues:[{propertyDefinitionId:dateId,type:"date",value:{precision:"day",start:"2026-09-02",end:null}}]})})));});
 it("sorts canonical decimal strings numerically without converting them to JavaScript numbers",()=>{const numberId="00000000-0000-4000-8000-000000000010";const numericCategory={...category,propertySchemaV2:[...category.propertySchemaV2!,{id:numberId,key:"score",name:"점수",type:"number" as const,required:false,system:false,config:{},order:2,version:1,deletedAt:null}]};const numericRecords=records.map((record,index)=>({...record,propertyValues:[{propertyDefinitionId:numberId,type:"number" as const,value:index===0?"10.00":"2.0"}]}));const numericView={...initial,sorts:[{propertyId:numberId,direction:"asc" as const,nulls:"last" as const}],visiblePropertyIds:[titleId,numberId],propertyOrder:[titleId,numberId]};render(<CareerViewShell category={numericCategory} initialView={numericView} initialPage={{data:numericRecords,page:{hasNextPage:false,nextCursor:null}}}/>);const rows=screen.getAllByRole("row").slice(1,3);expect(rows[0]?.textContent).toContain("기록 2");expect(rows[1]?.textContent).toContain("기록 1");});
 it("rolls back only the failed cell and marks it for retry",async()=>{const failingFetch=vi.fn(async(url:string,init?:RequestInit)=>{if(init?.method==="PATCH")return new Response(null,{status:500});return new Response(JSON.stringify({data:records[0]}),{status:200,headers:{"content-type":"application/json"}});});vi.stubGlobal("fetch",failingFetch);render(<CareerViewShell category={category} initialView={initial} initialPage={{data:records,page:{hasNextPage:false,nextCursor:null}}}/>);const title=screen.getByRole("gridcell",{name:"기록 1"});fireEvent.focus(title);fireEvent.keyDown(title,{key:"F2"});const input=screen.getByRole("textbox",{name:"제목 셀 편집"});fireEvent.change(input,{target:{value:"실패할 제목"}});fireEvent.keyDown(input,{key:"Enter"});await waitFor(()=>expect((screen.getByText("기록 1").closest('[role="gridcell"]') as HTMLElement | null)?.dataset.issue).toBe("true"));expect(screen.getByRole("gridcell",{name:"기록 2"})).toBeTruthy();});
});
