-- 마이그레이션이 함께 넣던 기본 데이터입니다.
-- 카테고리 기본 7종 · 요금제 · 지면 시드 · 정기 작업 정의.

insert into `plan` (`id`, `code`, `generation_quota`, `features`, `is_public_listed`) values
  ('aa09f35f-bde6-4e18-b9cd-7b32759bf43b', 'free', 3, cast('{"brew.cowork": false, "recipe.auto": true, "template.pro": false, "analytics.full": false, "export.document": false, "analysis.advanced": false, "collaboration.team": false, "portfolio.generate": true, "generation.unlimited": false, "publishing.remove_badge": false, "publishing.custom_domain": false, "analytics.returning_visitors": false, "analytics.organization_domains": false}' as json), 1),
  ('eb523ae9-c1cc-411b-a800-e02b081699d4', 'pro', 0, cast('{"brew.cowork": true, "recipe.auto": true, "template.pro": true, "analytics.full": true, "export.document": true, "analysis.advanced": false, "collaboration.team": false, "portfolio.generate": true, "generation.unlimited": true, "publishing.remove_badge": false, "publishing.custom_domain": false, "analytics.returning_visitors": false, "analytics.organization_domains": true}' as json), 1),
  ('3c39da65-e38f-47cf-9187-4f7a9306af12', 'team', 0, cast('{"brew.cowork": true, "recipe.auto": true, "template.pro": true, "analytics.full": true, "export.document": true, "analysis.advanced": true, "collaboration.team": true, "portfolio.generate": true, "generation.unlimited": true, "publishing.remove_badge": true, "publishing.custom_domain": true, "analytics.returning_visitors": true, "analytics.organization_domains": true}' as json), 1);

insert into `category` (`id`, `user_id`, `key`, `is_system`, `property_schema`, `sort_order`, `name`, `icon`, `default_view`, `version`, `updated_at`) values
  ('af5510dc-9717-4f1e-b0f9-4afd79aafe0f', null, 'project', 1, cast('{"role": {"type": "text", "label": "역할", "system": false, "required": false}, "outcome": {"type": "text", "label": "성과", "system": false, "required": false}, "technologies": {"type": "tags", "label": "기술", "system": false, "required": false}}' as json), 1, '프로젝트', 'folder-kanban', 'gallery', 1, '2026-08-21 08:22:24.373'),
  ('baa733dc-553d-4c5b-a58f-9ce6aa25b856', null, 'education_history', 1, cast('{"program": {"type": "text", "label": "과정", "system": false, "required": false}, "endMonth": {"type": "date", "label": "종료 월", "system": false, "required": false}, "startMonth": {"type": "date", "label": "시작 월", "system": false, "required": false}, "institution": {"type": "text", "label": "기관", "system": false, "required": false}}' as json), 2, '학력·이력', 'graduation-cap', 'timeline', 1, '2026-08-21 08:22:24.373'),
  ('f66dd6b1-2293-45ef-8604-a23286671dce', null, 'certification_award', 1, cast('{"issuer": {"type": "text", "label": "발급·수여 기관", "system": false, "required": false}, "issuedMonth": {"type": "date", "label": "취득 월", "system": false, "required": false}}' as json), 3, '자격증·수상', 'award', 'table', 1, '2026-08-21 08:22:24.373'),
  ('4b2df1dd-52df-4345-9c94-dfc64e84cec6', null, 'academic_writing', 1, cast('{"url": {"type": "text", "label": "원문 링크", "system": false, "required": false}, "publication": {"type": "text", "label": "게재처", "system": false, "required": false}, "publishedMonth": {"type": "date", "label": "게재 월", "system": false, "required": false}}' as json), 4, '학술·집필', 'book-open', 'list', 1, '2026-08-21 08:22:24.373'),
  ('ec2c9fb6-0e9f-4d5e-9ba3-3ee79d9a55ea', null, 'activity_leadership', 1, cast('{"role": {"type": "text", "label": "역할", "system": false, "required": false}, "outcome": {"type": "text", "label": "성과", "system": false, "required": false}, "organization": {"type": "text", "label": "조직", "system": false, "required": false}}' as json), 5, '활동·리더십', 'users', 'table', 1, '2026-08-21 08:22:24.373'),
  ('a0d3032e-762a-496b-b733-27e4688599e3', null, 'skill_tool', 1, cast('{"group": {"type": "text", "label": "분류", "system": false, "required": false}, "lastUsedMonth": {"type": "date", "label": "최근 사용 월", "system": false, "required": false}}' as json), 6, '스킬·도구', 'wrench', 'board', 1, '2026-08-21 08:22:24.373'),
  ('475106fc-bf88-4a73-9c27-66c648733936', null, 'experience', 1, cast('{"role": {"type": "text", "label": "역할", "system": false, "required": false}, "task": {"type": "text", "label": "맡은 일", "system": false, "required": false}, "action": {"type": "text", "label": "한 일", "system": false, "required": false}, "result": {"type": "text", "label": "결과", "system": false, "required": false}, "metrics": {"type": "tags", "label": "수치", "system": false, "required": false}, "situation": {"type": "text", "label": "상황", "system": false, "required": false}, "achievements": {"type": "tags", "label": "성과", "system": false, "required": false}, "competencies": {"type": "tags", "label": "역량", "system": false, "required": false}, "organization": {"type": "text", "label": "조직", "system": false, "required": false}}' as json), 0, '경험', 'briefcase', 'table', 2, '2026-08-21 08:22:24.458');

insert into `template` (`id`, `code`, `name`, `tone_tags`, `supported_sections`, `plan_required`, `description`, `renderer_version`, `style`, `industries`, `is_active`) values
  ('c42de58e-a0d3-4118-ab68-1a057324f7f1', 'clarity', 'Clarity', cast('["clear", "professional"]' as json), cast('["*"]' as json), 'free', 'Readable single-column evidence narrative', 1, cast('{"font": "sans", "text": "#1f2937", "accent": "#2563eb", "density": "comfortable", "structure": "single-column", "background": "#ffffff"}' as json), cast('["software", "technology"]' as json), 1),
  ('e1f697a4-ab3a-436a-913e-d214a65be422', 'signal', 'Signal', cast('["technical", "concise"]' as json), cast('["*"]' as json), 'free', 'Compact evidence-forward technical layout', 1, cast('{"font": "sans", "text": "#e2e8f0", "accent": "#38bdf8", "density": "compact", "structure": "dense-grid", "background": "#0f172a"}' as json), cast('["software", "data", "infrastructure"]' as json), 1),
  ('a3702f97-24e0-44ad-aff9-af895601dea1', 'editorial', 'Editorial', cast('["warm", "narrative"]' as json), cast('["*"]' as json), 'pro', 'Spacious narrative layout for detailed work', 1, cast('{"font": "serif", "text": "#3f2d20", "accent": "#9a3412", "density": "spacious", "structure": "wide-margin", "background": "#fffaf0"}' as json), cast('["design", "research", "writing"]' as json), 1);

insert into `scheduled_job_definition` (`job_key`, `interval_seconds`, `next_run_at`, `last_started_at`, `last_finished_at`, `last_status`, `failure_count`) values
  ('saved_searches', 3600, '2026-08-21 08:22:24.432', null, null, null, 0),
  ('expire_postings', 3600, '2026-08-21 08:22:24.432', null, null, null, 0),
  ('notification_batch', 300, '2026-08-21 08:22:24.432', null, null, null, 0),
  ('analytics_daily', 86400, '2026-08-21 08:22:24.432', null, null, null, 0),
  ('deletion_grace', 3600, '2026-08-21 08:22:24.432', null, null, null, 0),
  ('retention', 86400, '2026-08-21 08:22:24.432', null, null, null, 0),
  ('job_ingest', 86400, '2026-08-21 08:22:24.466', null, null, null, 0),
  ('posting_facts', 600, '2026-08-21 08:22:24.490', null, null, null, 0);
