import { randomUUID } from "node:crypto";
import { createMysqlResource } from "./src/platform/mysql.js";
import { IdentityService } from "./src/modules/identity/service.js";
import { JobBoardService } from "./src/modules/jobs/board-service.js";
import { buildApi } from "./src/api/build-app.js";
import { loadRuntimeConfig } from "./src/config/runtime-config.js";
process.env.DATABASE_URL = "mysql://expresso:expresso@127.0.0.1:53306/expresso";
process.env.REDIS_URL = "redis://127.0.0.1:56379";
process.env.AI_PROVIDER = "off";
const config = loadRuntimeConfig();
const sql = createMysqlResource(process.env.DATABASE_URL).sql;
const identity = new IdentityService(sql);
const app = buildApi({ config, identityService: identity, jobBoardService: new JobBoardService(sql) });
const planId = (await sql<{id:string}[]>`select id from plan where code = 'free'`)[0]!.id;
const userId = randomUUID();
await sql`insert into \`user\` (id, email, display_name, plan_id) values (${userId}, ${`app-${userId}@e.com`}, 'A', ${planId})`;
const token = (await identity.issueSession({ userId })).accessToken;
await app.ready();
const res = await app.inject({ method: "GET", url: "/v1/jobs/postings?q=zzz", headers: { authorization: `Bearer ${token}` } });
console.log(res.statusCode, res.body.slice(0, 400));
await sql`delete from \`user\` where id = ${userId}`;
await app.close();
