import type { Db, Collection } from "mongodb";
import type * as Docs from "./documents/index.js";

export interface MongoCollections {
  plans: Collection<Docs.PlanDoc>;
  users: Collection<Docs.UserDoc>;
  accountDeletionRequests: Collection<Docs.AccountDeletionRequestDoc>;
  accountDeletionEvents: Collection<Docs.AccountDeletionEventDoc>;
  companies: Collection<Docs.CompanyDoc>;
  jobPostings: Collection<Docs.JobPostingDoc>;
  jobAnalyses: Collection<Docs.JobAnalysisDoc>;
  brews: Collection<Docs.BrewDoc>;
  templates: Collection<Docs.TemplateDoc>;
  portfolios: Collection<Docs.PortfolioDoc>;
  deployments: Collection<Docs.DeploymentDoc>;
  analyticsEventReceipts: Collection<Docs.AnalyticsEventReceiptDoc>;
  annotations: Collection<Docs.AnnotationDoc>;
  interviewSessions: Collection<Docs.InterviewSessionDoc>;
  jobPostingRequirements: Collection<Docs.JobPostingRequirementDoc>;
  questions: Collection<Docs.QuestionDoc>;
  careerCategories: Collection<Docs.CareerCategoryDoc>;
  careerRecords: Collection<Docs.CareerRecordDoc>;
  answers: Collection<Docs.AnswerDoc>;
  answerRecordChanges: Collection<Docs.AnswerRecordChangeDoc>;
  recipes: Collection<Docs.RecipeDoc>;
  recipeSections: Collection<Docs.RecipeSectionDoc>;
  portfolioSections: Collection<Docs.PortfolioSectionDoc>;
  blocks: Collection<Docs.BlockDoc>;
  brewJobs: Collection<Docs.BrewJobDoc>;
  brewSources: Collection<Docs.BrewSourceDoc>;
  careerViews: Collection<Docs.CareerViewDoc>;
  companyResearchItems: Collection<Docs.CompanyResearchItemDoc>;
  consents: Collection<Docs.ConsentDoc>;
  visitEvents: Collection<Docs.VisitEventDoc>;
  conversionEvents: Collection<Docs.ConversionEventDoc>;
  dashboardViews: Collection<Docs.DashboardViewDoc>;
  deploymentSlugRedirects: Collection<Docs.DeploymentSlugRedirectDoc>;
  derivedMetrics: Collection<Docs.DerivedMetricDoc>;
  exportAssets: Collection<Docs.ExportAssetDoc>;
  exportJobs: Collection<Docs.ExportJobDoc>;
  generatedPages: Collection<Docs.GeneratedPageDoc>;
  generationJobs: Collection<Docs.GenerationJobDoc>;
  recipeItems: Collection<Docs.RecipeItemDoc>;
  recipeEvidencePaths: Collection<Docs.RecipeEvidencePathDoc>;
  generationSentenceEvidence: Collection<Docs.GenerationSentenceEvidenceDoc>;
  usageCounters: Collection<Docs.UsageCounterDoc>;
  generationUsageLedger: Collection<Docs.GenerationUsageLedgerDoc>;
  identityOauthAccounts: Collection<Docs.IdentityOauthAccountDoc>;
  identitySessions: Collection<Docs.IdentitySessionDoc>;
  insights: Collection<Docs.InsightDoc>;
  interests: Collection<Docs.InterestDoc>;
  jobSources: Collection<Docs.JobSourceDoc>;
  layoutSpecs: Collection<Docs.LayoutSpecDoc>;
  matchScores: Collection<Docs.MatchScoreDoc>;
  mediaAssets: Collection<Docs.MediaAssetDoc>;
  mediaVariants: Collection<Docs.MediaVariantDoc>;
  metricsDaily: Collection<Docs.MetricDailyDoc>;
  notifications: Collection<Docs.NotificationDoc>;
  outboxEvents: Collection<Docs.OutboxEventDoc>;
  portfolioEditProposals: Collection<Docs.PortfolioEditProposalDoc>;
  portfolioSnapshots: Collection<Docs.PortfolioSnapshotDoc>;
  recentSearches: Collection<Docs.RecentSearchDoc>;
  recipeRevisions: Collection<Docs.RecipeRevisionDoc>;
  recipeUnusedSources: Collection<Docs.RecipeUnusedSourceDoc>;
  recordLinks: Collection<Docs.RecordLinkDoc>;
  recordUsages: Collection<Docs.RecordUsageDoc>;
  requirementCoverages: Collection<Docs.RequirementCoverageDoc>;
  revisions: Collection<Docs.RevisionDoc>;
  savedSearches: Collection<Docs.SavedSearchDoc>;
  scheduledJobDefinitions: Collection<Docs.ScheduledJobDefinitionDoc>;
  scheduledJobRuns: Collection<Docs.ScheduledJobRunDoc>;
  sectionViews: Collection<Docs.SectionViewDoc>;
  skills: Collection<Docs.SkillDoc>;
  skillEvidence: Collection<Docs.SkillEvidenceDoc>;
  widgets: Collection<Docs.WidgetDoc>;
  schemaMigrations: Collection<Docs.SchemaMigrationDoc>;
  migrationLocks: Collection<Docs.MigrationLockDoc>;
  snapshotChunks: Collection<Docs.SnapshotChunkDoc>;
  analyticsRateLimits: Collection<Docs.AnalyticsRateLimitDoc>;
  importRuns: Collection<Docs.ImportRunDoc>;
  importCheckpoints: Collection<Docs.ImportCheckpointDoc>;
}

export function mongoCollections(db: Db): MongoCollections {
  return {
    plans: db.collection<Docs.PlanDoc>("plans"),
    users: db.collection<Docs.UserDoc>("users"),
    accountDeletionRequests: db.collection<Docs.AccountDeletionRequestDoc>("account_deletion_requests"),
    accountDeletionEvents: db.collection<Docs.AccountDeletionEventDoc>("account_deletion_events"),
    companies: db.collection<Docs.CompanyDoc>("companies"),
    jobPostings: db.collection<Docs.JobPostingDoc>("job_postings"),
    jobAnalyses: db.collection<Docs.JobAnalysisDoc>("job_analyses"),
    brews: db.collection<Docs.BrewDoc>("brews"),
    templates: db.collection<Docs.TemplateDoc>("templates"),
    portfolios: db.collection<Docs.PortfolioDoc>("portfolios"),
    deployments: db.collection<Docs.DeploymentDoc>("deployments"),
    analyticsEventReceipts: db.collection<Docs.AnalyticsEventReceiptDoc>("analytics_event_receipts"),
    annotations: db.collection<Docs.AnnotationDoc>("annotations"),
    interviewSessions: db.collection<Docs.InterviewSessionDoc>("interview_sessions"),
    jobPostingRequirements: db.collection<Docs.JobPostingRequirementDoc>("job_posting_requirements"),
    questions: db.collection<Docs.QuestionDoc>("questions"),
    careerCategories: db.collection<Docs.CareerCategoryDoc>("career_categories"),
    careerRecords: db.collection<Docs.CareerRecordDoc>("career_records"),
    answers: db.collection<Docs.AnswerDoc>("answers"),
    answerRecordChanges: db.collection<Docs.AnswerRecordChangeDoc>("answer_record_changes"),
    recipes: db.collection<Docs.RecipeDoc>("recipes"),
    recipeSections: db.collection<Docs.RecipeSectionDoc>("recipe_sections"),
    portfolioSections: db.collection<Docs.PortfolioSectionDoc>("portfolio_sections"),
    blocks: db.collection<Docs.BlockDoc>("blocks"),
    brewJobs: db.collection<Docs.BrewJobDoc>("brew_jobs"),
    brewSources: db.collection<Docs.BrewSourceDoc>("brew_sources"),
    careerViews: db.collection<Docs.CareerViewDoc>("career_views"),
    companyResearchItems: db.collection<Docs.CompanyResearchItemDoc>("company_research_items"),
    consents: db.collection<Docs.ConsentDoc>("consents"),
    visitEvents: db.collection<Docs.VisitEventDoc>("visit_events"),
    conversionEvents: db.collection<Docs.ConversionEventDoc>("conversion_events"),
    dashboardViews: db.collection<Docs.DashboardViewDoc>("dashboard_views"),
    deploymentSlugRedirects: db.collection<Docs.DeploymentSlugRedirectDoc>("deployment_slug_redirects"),
    derivedMetrics: db.collection<Docs.DerivedMetricDoc>("derived_metrics"),
    exportAssets: db.collection<Docs.ExportAssetDoc>("export_assets"),
    exportJobs: db.collection<Docs.ExportJobDoc>("export_jobs"),
    generatedPages: db.collection<Docs.GeneratedPageDoc>("generated_pages"),
    generationJobs: db.collection<Docs.GenerationJobDoc>("generation_jobs"),
    recipeItems: db.collection<Docs.RecipeItemDoc>("recipe_items"),
    recipeEvidencePaths: db.collection<Docs.RecipeEvidencePathDoc>("recipe_evidence_paths"),
    generationSentenceEvidence: db.collection<Docs.GenerationSentenceEvidenceDoc>("generation_sentence_evidence"),
    usageCounters: db.collection<Docs.UsageCounterDoc>("usage_counters"),
    generationUsageLedger: db.collection<Docs.GenerationUsageLedgerDoc>("generation_usage_ledger"),
    identityOauthAccounts: db.collection<Docs.IdentityOauthAccountDoc>("identity_oauth_accounts"),
    identitySessions: db.collection<Docs.IdentitySessionDoc>("identity_sessions"),
    insights: db.collection<Docs.InsightDoc>("insights"),
    interests: db.collection<Docs.InterestDoc>("interests"),
    jobSources: db.collection<Docs.JobSourceDoc>("job_sources"),
    layoutSpecs: db.collection<Docs.LayoutSpecDoc>("layout_specs"),
    matchScores: db.collection<Docs.MatchScoreDoc>("match_scores"),
    mediaAssets: db.collection<Docs.MediaAssetDoc>("media_assets"),
    mediaVariants: db.collection<Docs.MediaVariantDoc>("media_variants"),
    metricsDaily: db.collection<Docs.MetricDailyDoc>("metrics_daily"),
    notifications: db.collection<Docs.NotificationDoc>("notifications"),
    outboxEvents: db.collection<Docs.OutboxEventDoc>("outbox_events"),
    portfolioEditProposals: db.collection<Docs.PortfolioEditProposalDoc>("portfolio_edit_proposals"),
    portfolioSnapshots: db.collection<Docs.PortfolioSnapshotDoc>("portfolio_snapshots"),
    recentSearches: db.collection<Docs.RecentSearchDoc>("recent_searches"),
    recipeRevisions: db.collection<Docs.RecipeRevisionDoc>("recipe_revisions"),
    recipeUnusedSources: db.collection<Docs.RecipeUnusedSourceDoc>("recipe_unused_sources"),
    recordLinks: db.collection<Docs.RecordLinkDoc>("record_links"),
    recordUsages: db.collection<Docs.RecordUsageDoc>("record_usages"),
    requirementCoverages: db.collection<Docs.RequirementCoverageDoc>("requirement_coverages"),
    revisions: db.collection<Docs.RevisionDoc>("revisions"),
    savedSearches: db.collection<Docs.SavedSearchDoc>("saved_searches"),
    scheduledJobDefinitions: db.collection<Docs.ScheduledJobDefinitionDoc>("scheduled_job_definitions"),
    scheduledJobRuns: db.collection<Docs.ScheduledJobRunDoc>("scheduled_job_runs"),
    sectionViews: db.collection<Docs.SectionViewDoc>("section_views"),
    skills: db.collection<Docs.SkillDoc>("skills"),
    skillEvidence: db.collection<Docs.SkillEvidenceDoc>("skill_evidence"),
    widgets: db.collection<Docs.WidgetDoc>("widgets"),
    schemaMigrations: db.collection<Docs.SchemaMigrationDoc>("schema_migrations"),
    migrationLocks: db.collection<Docs.MigrationLockDoc>("migration_locks"),
    snapshotChunks: db.collection<Docs.SnapshotChunkDoc>("snapshot_chunks"),
    analyticsRateLimits: db.collection<Docs.AnalyticsRateLimitDoc>("analytics_rate_limits"),
    importRuns: db.collection<Docs.ImportRunDoc>("import_runs"),
    importCheckpoints: db.collection<Docs.ImportCheckpointDoc>("import_checkpoints"),
  };
}
